name: Deploy Website

on:
  push:
    branches: [ master ]  # This will trigger deployment when you push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Copy server files to dist
      run: |
        mkdir -p dist/api
        cp -r api/* dist/api/
        cp .htaccess dist/
        cp index.php dist/
        cp deploy.php dist/
        cp generate_api.php dist/
        cp setup_database.php dist/
        cp web.config dist/
        cp schema.sql dist/
      continue-on-error: true
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
        dangerous-clean-slate: false  # Changed to false to preserve files not in the local directory
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**