name: Deploy Website

on:
  push:
    branches: [ master ]  # This will trigger deployment when you push to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Copy server files to dist
      run: |
        mkdir -p dist/api
        cp -r api/* dist/api/
        
        # Create config.php file
        cat > dist/api/config.php << 'EOL'
        <?php
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH');
        header('Access-Control-Allow-Headers: Content-Type, Authorization');
        header('Content-Type: application/json');
        
        $host = 'localhost';
        $db_name = 'attcly_db';
        $username = 'attcly_dbuser';
        $password = 'Na0797637745!!';
        $conn = null;
        
        try {
            $conn = new PDO("mysql:host=$host;dbname=$db_name", $username, $password);
            $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } catch(PDOException $e) {
            echo json_encode(['error' => 'Connection failed: ' . $e->getMessage()]);
            die();
        }
        ?>
        EOL
        
        # Create .htaccess for API routing
        cat > dist/api/.htaccess << 'EOL'
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule ^([^/]+)/?$ $1.php [L]
        RewriteRule ^([^/]+)/([^/]+)/?$ $1.php/$2 [L]
        EOL
        
        cp .htaccess dist/
        cp index.php dist/
        cp deploy.php dist/
        cp generate_api.php dist/
        cp setup_database.php dist/
        cp web.config dist/
        cp schema.sql dist/
      continue-on-error: true
      
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /
        dangerous-clean-slate: false  # Changed to false to preserve files not in the local directory
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**